# Generated by Django 2.2.5 on 2019-10-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('minimum_price', models.FloatField(default=0.0)),
                ('deadline_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=1024)),
            ],
        ),
    ]
