# Generated by Django 2.2.5 on 2019-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='auctioneer',
            field=models.CharField(default='', max_length=256),
        ),
    ]
