# Generated by Django 2.2.5 on 2019-10-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_item_auctioneer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='new_bid',
            field=models.FloatField(default=0.0),
        ),
    ]
