# Generated by Django 2.2.5 on 2019-10-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_item_new_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='new_bid',
            new_name='new_price',
        ),
    ]
