# Generated by Django 2.2.5 on 2019-10-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20191012_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bidder',
            field=models.CharField(default='', max_length=256),
        ),
    ]
