# Generated by Django 2.2.5 on 2019-11-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20191013_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='detail',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='item',
            name='message',
            field=models.CharField(default='', max_length=512),
        ),
    ]
