# Generated by Django 2.2.5 on 2019-11-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20191101_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='max_bid',
            new_name='current_price',
        ),
    ]
